# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
## main branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "monday"
    time: "02:30" # 2.30am utc
  target-branch: main
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major bumps in main, as it breaks the group bump process
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/api"
  - "/hack/tools"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "03:00" # 3am utc
  target-branch: main
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
## main branch config ends here

## release-1.12 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "monday"
    time: "03:30" # 3.30am utc
  target-branch: release-1.12
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/api"
  - "/hack/tools"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "04:00" # 4am utc
  target-branch: release-1.12
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # golang.org/x/* only releases minors no patches, so minors have to be allowed
  - dependency-name: "golang.org/x/*"
    update-types: ["version-update:semver-major"]
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## release-1.12 branch config ends here

## release-1.11 branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "monday"
    time: "04:30" # 4.30am utc
  target-branch: release-1.11
  ## group all action bumps into single PR
  groups:
    github-actions:
      patterns: ["*"]
  ignore:
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"
  # Go
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/api"
  - "/hack/tools"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "05:00" # 5am utc
  target-branch: release-1.11
  groups:
    kubernetes:
      patterns: ["k8s.io/*"]
    capi:
      patterns: ["sigs.k8s.io/cluster-api", "sigs.k8s.io/cluster-api/test"]
  ignore:
  # golang.org/x/* only releases minors no patches, so minors have to be allowed
  - dependency-name: "golang.org/x/*"
    update-types: ["version-update:semver-major"]
  # Ignore major and minor bumps for release branch
  - dependency-name: "*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## release-1.11 branch config ends here
